### ISSUE TITLE
Great project but does not seem to be working on windows...

### ISSUE THREAD

**Issue by H3RSKO** [hellgrenj/apod-wp#6]
I installed and ran with my own api code but get the following errors:

```
ok, here we go..

(node:10780) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10780) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:10780) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
√ fetching metadata
√ fetching high resolution APOD
√ writing text to image
× failed with Error: spawn UNKNOWN

.... eehhmm ...well thats embarrassing.. im sorry!
```

Any ideas?

**Comment by hellgrenj** [comment]
I haven't touched this in forever so the dependencies were outdated. This old version still worked for me on Windows tho.. but with the ugly warnings...  When i upgraded the dependencies the warnings went away and it  works on my PC with Windows and on my Macbook with Node v 16.1.0 (current). I published a new npm package so uninstall the package (npm uninstall apod-wp -g) and re-install it (npm install apod-wp -g) to get the latest package.. if it still doesn't work for you my guess is that it has to do with permissions or something on your machine...

**Comment by H3RSKO** [comment]
Still not working, now I get this error:

```ok, here we go..

√ fetching metadata
- fetching metadata
√ fetching high resolution APOD
- fetching high resolution APOD
√ writing text to image
- writing text to image
× failed with Error: spawn UNKNOWN

.... eehhmm ...well thats embarrassing.. im sorry!
```

I'll have to check out my permissions. Thanks!

**Comment by hellgrenj** [comment]
Yeah I think so. I actually tried the package on 2 more windows computers now and I can't reproduce the issue you are describing. You are always welcome to clone the code, do some debugging and contribute a fix (PR) if it turns out that its a bug in the application.
